# Generated by Django 5.2.8 on 2025-11-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
